### ISSUE TITLE
Reprint not recognising prints or HW

### ISSUE THREAD

**Issue by theblixguy** [ajalt/reprint#20]
I am using the latest version of the library. My users are reporting that my app is no longer recognising fingerprints registered on device and sometimes not even the fingerprint hardware. Example devices - OnePlus 2 and Cubot cheetah 2. I personally tested on Android Emulator (running 7.1.1) and a Samsung J7 Prime and it worked, but not sure why it doesn't work on others. 

Funny thing is, it used to work before (when using v2.5.6), but I updated the library to the latest version today in my app and it broke support for some devices.

**Comment by ajalt** [comment]
Hm, I don't have either of the two phones you listed, and I'm not able to reproduce that on any of the devices I have available. Let me know if you find out any more information.

**Comment by theblixguy** [comment]
This issue seems related: http://stackoverflow.com/questions/36031092/fingerprintmanager-ishardwaredetected-throwing-java-lang-securityexception

On those devices I mentioned, it seems like there's an exception both when trying to detect fingerprint HW and fingerprint enrolment so the methods return false. Maybe you should add some logging to your library (for example, when checking whether the hardware is present on not) so it's easier to detect the root cause of an issue, like this one.

**Comment by ajalt** [comment]
I certainly could add the ability to register a logger with Reprint. What kind of logging would you like to see?

**Comment by theblixguy** [comment]
Basically just printing exception stack trace instead of simply catching and ignoring it. 

One of my users downgraded to an older version of the app (which is using an older version of the library) and the issue vanished so there's definitely something wrong with the library. I'm interested in finding out what it is, but the logcat doesn't contain any issue and logging could be of some help.

**Comment by theblixguy** [comment]
BTW here's my app if you want to test it: github.com/theblixguy/DroidID

**Comment by aritraroy** [comment]
I am also facing the same problem. Some of my users are complaining that suddenly they are seeing "No fingerprint hardware detected" message, but it used to work previously. I have changed nothing in code that could make this happen. Many users are unable to login to the app just because of this weird problem. Any ideas on why this can happen?

**Comment by ajalt** [comment]
I released version `2.9.0`, which adds an optional logging interface that you can use to get more information about unexpected errors by passing an instance to `Reprint.initialize`.

You can see an example of its usage in the sample app here: https://github.com/ajalt/reprint/blob/master/sample/src/main/java/com/github/ajalt/reprint/App.java#L12

The sample just writes messages to logcat, but you'll of course want to send the messages to your crash reporter of choice.

Let me know if you find out anything.

**Comment by aritraroy** [comment]
Let me give it a try and get back to you when some user faced the issue again and I get the logs.

**Comment by ajalt** [comment]
Given that the symptoms you're reporting match this issue:
https://code.google.com/p/android/issues/detail?id=231939
I'm going to say that this is a google bug, and not a problem with Reprint itself. I'll leave this issue open until that android issue is resolved. Let me know if you think that there is a different problem.

**Comment by ajalt** [comment]
Ok, so I think I implemented a workaround for the appcompat bug in 6d51ff8.

I stopped using appcompat almost entirely, since we're already wrapping all the methods. Try updating to Reprint 2.9.1 and let me know if there are still any issues.

**Comment by aritraroy** [comment]
Thanks for the update. I think the issue is fixed. Let me push an update and check with some of my users who had reported a problem.

**Comment by ajalt** [comment]
Just a heads up: 2.9.1 introduced a regression that could cause a crash on KitKat and Lollipop devices. You should upgrade to 2.9.2 as soon as possible. Sorry about that.

**Comment by aritraroy** [comment]
Thanks for the update. I was just going to push an update to my app and you have told me at the right time. 👍 

Btw, was curious to know what went wrong actually. Initially, everything was working fine all devices. Then I updated from 2.8.0 to 2.8.3 and some of my users started reporting that the fingerprint scanner was not detecting. 

So, if the issue is in the FingerprintManagerCompat then how was everything working well before 2.8.0?

**Comment by ajalt** [comment]
The bug was introduced in appcompat 25.1.0, which I upgraded to in Reprint version 2.8.0. It would report that there was no fingerprint hardware on some devices that do in fact have it. The bug still exists in the latest appcompat version, so instead of requiring users to use an old version of appcompat, I just stopped using FingerprintManagerCompat and implemented that functionality myself.

**Comment by aritraroy** [comment]
I see. Thanks for your efforts.
